openapi: 3.1.0
info:
  title: Error Schemas
  version: 1.0.0
components:
  schemas:
    InternalServerError:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Internal Server Error
        errorCode:
          type: string
          enum: ["INTERNAL_SERVER_ERROR"]
          example: INTERNAL_SERVER_ERROR
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
    ValidationErrorInvalidRequestBody:
      type: object
      required:
        - success
        - message
        - errorCode
        - requestId
        - errors
      properties:
        success:
          type: boolean
          enum: [false]
          example: false
        message:
          type: string
          example: Validation failed, some fields in the request body did not meet the expected format or constraints.
        errorCode:
          type: string
          enum: ["VALIDATION_ERROR_INVALID_REQUEST_BODY"]
          example: VALIDATION_ERROR_INVALID_REQUEST_BODY
        requestId:
          type: string
          example: cc5065df0c6b4c19970d4e92f
        errors:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
              message:
                type: string
          example:
            - field: email
              message: Invalid email address
            - field: password
              message: Password must be at least 8 characters
